name = "fileuni-docs"
compatibility_date = "2026-02-23"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = "./dist"
not_found_handling = "404-page"

[vars]
SITE_URL = "https://docs.fileuni.com/"
